---
apiVersion: v1
kind: Namespace
metadata:
  name: game-2048

---



kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  namespace: game-2048
  labels:
    app: apple
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - "-text=apple"

---

kind: Service
apiVersion: v1
metadata:
  name: apple-service
  namespace: game-2048
spec:
  selector:
    app: apple
  ports:
    - port: 5678 # Default port for image




            
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apple-ingress
  namespace: game-2048
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: apple-service
            port:
              number: 5678
